wait for API added

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -16,6 +16,33 @@ buildLivenessCheck: &buildLivenessCheck
       .circleci/check-workflow-live.sh
 
 
+waitForAPI: &waitForAPI
+  run:
+    name: Wait for the API server to be up
+    command: |
+      export API_HOSTNAME=localhost
+      export API_PORT=8000
+      export METADATA_URL="https://${API_HOSTNAME}:${API_PORT}/v1/metadata"
+      echo "METADATA_URL is set to ${METADATA_URL}"
+      set +e
+      SUCCESS=0
+      for i in $(seq 1 25); do
+        metadata="$(curl -sk --connect-timeout 5 --max-time 10 "${METADATA_URL}")"
+        if [[ $? -eq 0 && "$(jq '.licenseStatus' -r \<<<"$metadata")" != "RESTARTING" ]]; then
+          SUCCESS=1
+          break
+        fi
+        sleep 5
+      done
+      if [[ "${SUCCESS}" == 0 ]]; then
+        kubectl -n stackrox get pod
+        echo "Failed to connect to Central"
+        exit 1
+      fi
+      cci-export API_HOSTNAME "$API_HOSTNAME"
+      cci-export API_PORT "$API_PORT"
+      cci-export API_ENDPOINT "${API_HOSTNAME}:${API_PORT}"
+
 setupGoogleAppCreds: &setupGoogleAppCreds
   run:
     name: Setup GCloud Service Account
@@ -30,7 +57,6 @@ setupGoogleAppCreds: &setupGoogleAppCreds
 connectToCentral: &connectToCentral
   run:
     name: Connect to monitoring via port-forward on 443
-
     command: |
       set +e
       nohup kubectl -n stackrox port-forward service/central 8000:443
@@ -125,7 +151,10 @@ jobs:
       - run:
           name: Generate central bundle
           command: |
-            ./roxctl central generate k8s pvc --main-image docker.io/stackrox/main:3.0.35.0  --scanner-image docker.io/stackrox/scanner:2.0.1 --scanner-db-image docker.io/stackrox/scanner-db:2.0.1
+            ./roxctl central generate k8s pvc \
+                --main-image docker.io/stackrox/main:3.0.35.0 \
+                --scanner-image docker.io/stackrox/scanner:2.0.1 \
+                --scanner-db-image docker.io/stackrox/scanner-db:2.0.1 \
 
             export ROX_PASSWORD=$(cat central-bundle/password)
             cci-export ROX_USERNAME "admin"
@@ -143,6 +172,8 @@ jobs:
             central-bundle/scanner/scripts/setup.sh
             kubectl create -R -f central-bundle/scanner
 
+      - *waitForAPI
+
       - *setupGoogleAppCreds
 
       - run:
@@ -156,17 +187,20 @@ jobs:
       - run:
          name: Add license key to central
          command: |
-           export API_HOSTNAME=localhost
-           export API_PORT=8000
-           cci-export API_HOSTNAME $API_HOSTNAME
-           cci-export API_PORT $API_PORT
-           ./roxctl central license add --license="${ROX_LICENSE_KEY}" -e "${API_HOSTNAME}:${API_PORT}" --insecure-skip-tls-verify
+           ./roxctl central license add \
+                    --license="${ROX_LICENSE_KEY}" \
+                    -e "${API_HOSTNAME}:${API_PORT}" \
+                    --insecure-skip-tls-verify \
 
 
       - run:
           name: Deploy sensor the remote cluster
           command: |
-            ./roxctl sensor generate k8s --name remote01 --collection-method kernel-module --collector-image stackrox/collector  --image docker.io/stackrox/main:3.0.35.0 -e "${API_HOSTNAME}:${API_PORT}" -p "${ROX_PASSWORD}"
+            ./roxctl sensor generate k8s --name remote01 \
+                                         --collection-method kernel-module \
+                                         --collector-image stackrox/collector \
+                                         --image docker.io/stackrox/main:3.0.35.0 \
+                                         -e "${API_HOSTNAME}:${API_PORT}" -p "${ROX_PASSWORD}" \
             ./sensor-remote/sensor.sh
             docker rm ${containerId}
 
