pr for jenkins deployment

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -15,6 +15,84 @@ buildLivenessCheck: &buildLivenessCheck
     command: |
       .circleci/check-workflow-live.sh
 
+
+
+jenkinsDeployment: &jenkinsDeployment
+  run:
+    name: Jenkins Deployment and wait for jenkins to be setup
+    command: |
+      kubectl create namespace qa
+      kubectl apply -f jenkins
+
+
+setUpPlugin: &setUpPlugin
+  run:
+    name: Installing the plugin on the Jenkins service
+    command: |
+      set +e
+      SUCCESS=1
+      export JENKINSPORT="8080"
+      for i in $(seq 1 50); do
+        export JENKINSPOD="$(kubectl get pods -n qa  -o=jsonpath='{range .items[*]}{.metadata.name}')"
+        if [[ ! -z "${JENKINSPOD}" ]]; then
+           SUCCESS=0
+           echo "Jenkins Pod is ready"
+           echo "JENKINSPOD is running on ${JENKINSPOD}"
+           break
+        fi
+      done
+      if [[ "${SUCCESS}" == 1 ]]; then
+           kubectl -n qa describe deploy
+           kubectl -n qa describe rs
+           kubectl -n qa get svc
+           kubectl -n qa get pods
+           echo "Failed to deploy jenkins pod"
+      fi
+      kubectl cp /home/circleci/jenkins-plugin/stackrox-k8s-security-platform/target/stackrox-k8s-security-platform.hpi qa/${JENKINSPOD}:/var/jenkins_home/plugins/.
+      output="$(kubectl -n qa  exec -i ${JENKINSPOD} ls /var/jenkins_home/plugins/stackrox-k8s-security-platform.hpi)"
+      if [[ $? -eq 0 ]]; then
+          echo "Jenkins plugin has been installed"
+      fi
+      export JENKINSVC=$(kubectl get svc -n qa jenkinsep -o jsonpath="{.status.loadBalancer.ingress[*].ip}")
+      echo Jenkins svc is running on "${JENKINSVC}"
+      echo restarting jenkins
+      export JENKINS_URL="http://${JENKINSVC}:${JENKINSPORT}/"
+      curl -XPOST "${JENKINS_URL}/restart"
+      for i in $(seq 1 50); do
+        output="$(curl -sk --connect-timeout 5 --max-time 10 "${JENKINS_URL}")"
+        if [[ $output == *"<title>Dashboard [Jenkins]</title>"* ]]; then
+             break
+             echo "stackrox plugin installation on Jenkins is complete"
+        fi
+        sleep 5
+      done
+      echo "Jenkins installation is complete"
+
+
+waitForJenkins: &waitForJenkinsService
+  run:
+    name: Wait for the Jenkins server to come up
+    command: |
+      set +e
+      SUCCESS=1
+      export JENKINS_PORT=8080
+      for i in $(seq 1 50); do
+        export JENKINS_SVC="$(kubectl get svc -n qa jenkinsep -o jsonpath="{.status.loadBalancer.ingress[*].ip}")"
+        export JENKINS_URL="http://${JENKINS_SVC}:${JENKINS_PORT}/"
+        output="$(curl -sk --connect-timeout 5 --max-time 10 "${JENKINS_URL}")"
+        if [[ $output == *"<title>Dashboard [Jenkins]</title>"* ]]; then
+          SUCCESS=0
+          break
+        fi
+        sleep 5
+      done
+      if [[ "${SUCCESS}" == 1 ]]; then
+          kubectl -n qa get pods
+          echo "Failed to deploy jenkins server"
+      fi
+      echo "JENKINS_URL is set to ${JENKINS_URL}"
+
+
 setupGoogleAppCreds: &setupGoogleAppCreds
   run:
     name: Setup GCloud Service Account
@@ -163,6 +241,7 @@ jobs:
           name: Generate central bundle
           command: |
             ./roxctl central generate k8s pvc \
+              --password jenkinsPlugin \
               --license /tmp/data.lic \
               --main-image "${IMAGE_NAME}" \
               --scanner-image docker.io/stackrox/scanner:2.0.4 \
@@ -185,6 +264,9 @@ jobs:
 
       - *waitForCentral
       - *connectToCentral
+      - *jenkinsDeployment
+      - *waitForJenkinsService
+      - *setUpPlugin
       - *collectK8sLogs
       - *storeK8sLogs
       - *deleteClusterk8s
