Add wait for api for central

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -26,6 +26,31 @@ setupGoogleAppCreds: &setupGoogleAppCreds
       gcloud auth activate-service-account --key-file /tmp/gcp.json
       gcloud auth list
 
+waitForAPI: &waitForAPI
+  run:
+    name: Wait for the API server to be up
+    command: |
+      export API_HOSTNAME=localhost
+      export API_PORT=8000
+      export METADATA_URL="https://${API_HOSTNAME}:${API_PORT}/v1/metadata"
+      echo "METADATA_URL is set to ${METADATA_URL}"
+      set +e
+      SUCCESS=0
+      for i in $(seq 1 25); do
+        metadata="$(curl -sk --connect-timeout 5 --max-time 10 "${METADATA_URL}")"
+        if [[ $? -eq 0 ]]; then
+          SUCCESS=1
+          echo "central is up and running"
+          break
+        fi
+        sleep 5
+      done
+      if [[ "${SUCCESS}" == 0 ]]; then
+        kubectl -n stackrox get pod
+        echo "Failed to connect to Central"
+        exit 1
+      fi
+
 storeK8sLogs: &storeK8sLogs
   store_artifacts:
     path: /tmp/k8s-service-logs
@@ -178,6 +203,7 @@ jobs:
             central-bundle/scanner/scripts/setup.sh
             kubectl create -R -f central-bundle/scanner
 
+      - *waitForAPI
       - *connectToCentral
       - *collectK8sLogs
       - *storeK8sLogs
