adding more debugging to check error

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -23,16 +23,14 @@ jenkinsDeployment: &jenkinsDeployment
     command: |
       kubectl create namespace qa
       kubectl apply -f jenkins
-      sleep 60
 
 setUpJenkinsL: &setUpJenkins
   run:
     name: setting up Jenkins
     command: |
+      sleep 60
       export JENKINSPOD=$(kubectl get pods -n qa  -o=jsonpath='{range .items[*]}{.metadata.name}')
       export JENKINSPORT=8080
-      echo "Jenkins Pod"
-      echo $JENKINSPOD
       echo "kubectl cp workspace/stackrox-k8s-security-platform/target/stackrox-k8s-security-platform.hpi
                           qa/$JENKINSPOD:/var/jenkins_home/plugins/stackrox-k8s-security-platform.hpi"
       kubectl cp workspace/stackrox-k8s-security-platform/target/stackrox-k8s-security-platform.hpi
@@ -52,7 +50,43 @@ waitForJenkins: &waitForJenkins
       export JENKINS_PORT=8080
       export JENKINS_URL="https://${JENKINS_SVC}:${JENKINS_PORT}/"
       echo "JENKINS_URL is set to ${JENKINS_URL}"
-      cci-export JENKINS_URL ${JENKINS_URL}
+      set +e
+      SUCCESS=0
+      for i in $(seq 1 25); do
+        output="$(curl -sk --connect-timeout 5 --max-time 10 "${JENKINS_URL}")"
+        if [[ $output != ""  ]]; then
+          SUCCESS=1
+          break
+        fi
+        sleep 5
+      done
+
+waitForAPI: &waitForAPI
+  run:
+    name: Wait for the API server to be up
+    command: |
+      export API_HOSTNAME=localhost
+      export API_PORT=8000
+      export API_ENDPOINT="https://${API_HOSTNAME}:${API_PORT}/v1/metadata"
+      echo "API_END_POINT is set to ${API_ENDPOINT}"
+      set +e
+      SUCCESS=0
+      for i in $(seq 1 25); do
+        output="$(curl -sk --connect-timeout 5 --max-time 10 "${API_ENDPOINT}")"
+        if [[ $? -eq 0 && "$(jq '.licenseStatus' -r \<<<"$metadata")" != "RESTARTING" ]]; then
+          SUCCESS=1
+          break
+        fi
+        sleep 5
+      done
+      if [[ "${SUCCESS}" == 0 ]]; then
+        kubectl -n stackrox get pod
+        echo "Failed to connect to Central"
+        exit 1
+      fi
+      cci-export API_HOSTNAME "$API_HOSTNAME"
+      cci-export API_PORT "$API_PORT"
+      cci-export API_ENDPOINT "${API_HOSTNAME}:${API_PORT}"
 
 setupGoogleAppCreds: &setupGoogleAppCreds
   run:
